### ISSUE TITLE
document what the out of memory behavior is

### ISSUE THREAD

**Issue by diwu1989** [getcarina/feedback#22]
There's a memory limit, what happens when the container hits the memory wall and crash?
Does the container get restart automatically from scratch or is it just stuck in the crashed state?

**Comment by rgbkrk** [comment]
Thanks for asking. This would make a great article on github.com/carina/getcarina.com

Since Carina containers are Docker containers, the native docker, swarm tooling, API, and practices are the way to go. You can set the restart behavior when launching your containers. To always restart on failure and exit you can use  `--restart=always`.

As for the inside of your container, your app has to know what to do in situations where it can't allocate memory. This differs in many cases, sometimes you want to just restart, shake it off, and read the logs after. Other times you want to catch it explicitly and log it appropriately.

**Comment by onthecly** [comment]
Hi there,

This will be added to our article list for the next release.  Thanks for sending in this suggestion.

**Comment by everett-toews** [comment]
Tracking this in https://github.com/getcarina/getcarina.com/issues/567
